version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "python polling.py" # "uvicorn main:app --port 8000 --host 0.0.0.0"
    ports:
      - 80:8000
    image: wishbot-dev
    hostname: abra-api
    container_name: wishbot-dev
    volumes:
      - "./:/api"
    env_file:
      - .env
